### ISSUE TITLE
LaTeX math formulas aren't rendered on Firefox

### ISSUE THREAD

**Issue by romain-michalec** [EPCCed/archer-gpu-course#2]
Hi, in the first and second exercises (cuda-intro and cuda-optimise), the inline math (`$...$`) and display math (`<script type="math/tex; mode=display">...</script>`) are not rendered correctly using:

* Firefox 71 and 72 on Ubuntu (me)
* Firefox on Windows (my neighbor)

The inline math is left as is and the display math is not rendered at all, see attached screenshots. Is this Firefox-specific? Are we supposed to install some extension to render this code?

![Screenshot_2020-01-09 Introduction A first CUDA program](https://user-images.githubusercontent.com/4263570/72114022-3182d900-333a-11ea-95dd-a4ec5aa28633.png)
![Screenshot_2020-01-09 Introduction Optimsing a CUDA application](https://user-images.githubusercontent.com/4263570/72114023-321b6f80-333a-11ea-92de-52f8ac78815a.png)

**Comment by tkoskela** [comment]
They didn't render for me either. Was using Chrome on MacOS Catalina.
